version: '3.8'

# Portainer'a build sırasında BuildKit kullanmamasını söyler
x-build:
  DOCKER_BUILDKIT: 0
  COMPOSE_DOCKER_CLI_BUILD: 0

services:
  bot:
    build: .
    container_name: unog-bot
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./data:/app/data