services:
  bot:
    build: .
    container_name: unog-bot
    restart: unless-stopped
    # network_mode: host
    ports: 
      - "8585:80"
    env_file:
      - .env
    volumes:
      - ./data:/app/data