FROM node:26-alpine AS builder

WORKDIR /app

COPY package*.json .
RUN npm ci

COPY . .
RUN npm run build

FROM node:26-alpine

WORKDIR /app

COPY package*.json .
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist
COPY ./config.toml .
RUN ls
CMD [ "npm", "start" ]